services:
  fastapi-app:
    build: ./Server_API
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - iot-network
    restart: always

  web-app:
    image: webapp:latest
    container_name: webapp
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://fastapi-app:8000
      - PORT=3000
      - NIXPACKS=1
    depends_on:
      - fastapi-app
    networks:
      - iot-network
    restart: always

networks:
  iot-network:
    driver: bridge
